# Sponsorship and funding options for this project

github: [ranas-mukminov]
patreon: # Add your Patreon username here
open_collective: # Add your Open Collective username here
custom: ['https://run-as-daemon.ru/support']
