name: Feature Request
description: Suggest a new feature or improvement for the Grafana Docker Dashboard
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when I need to monitor container restart counts but there's no panel for it..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: "Add a new panel that shows container restart count using the container_start_time_seconds metric..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered.
      placeholder: "I considered using Grafana's external dashboard, but it would be better to have it built into this one..."
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New panel / visualization
        - New metric or data source
        - Dashboard variable improvement
        - Query optimization
        - UI/UX improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: |
        In our production environment, we run 100+ containers across 10 Docker hosts.
        We frequently need to identify containers that are restarting due to errors.
        Having a restart count panel would help us quickly spot problematic containers.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Faster incident response
        - Better visibility into container health
        - Reduces time spent in Prometheus console
    validations:
      required: false

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - "Yes, I can submit a pull request"
        - "Yes, but I need guidance"
        - "No, I need someone else to implement it"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: If you have technical ideas on how to implement this, share them here.
      placeholder: |
        The metric we could use is:
        container_start_time_seconds{job="cadvisor"}
        
        We can calculate restarts using:
        changes(container_start_time_seconds[1h])
        
        Panel configuration:
        - Type: Table or Graph
        - Sort by restart count descending
        - Color code: Green (0 restarts), Yellow (1-5), Red (>5)
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Link to similar implementations or examples.
      placeholder: |
        Similar panel in another dashboard: https://grafana.com/grafana/dashboards/12345
        PromQL query reference: https://prometheus.io/docs/prometheus/latest/querying/functions/#changes
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the dashboard's purpose (Docker monitoring)
          required: true
        - label: I've considered if this could be a separate dashboard instead
          required: false
